### ISSUE TITLE
No way to distinguish between target related metrics and exporter metrics

### ISSUE THREAD

**Issue by dmitry-sinina** [mrlhansen/idrac_exporter#106]
According to documentation some metrics like **idrac_exporter_build_info** and **idrac_exporter_scrape_errors_total** relates not to scraped target but to exporter itself. With provided prometheus relabeling config **instance** label will be added to such metrics so instead of one idrac_exporter_scrape_errors_total we will have this metric for every target.

It would be great to export all target related metrics with label **target** and exporter related metrics without such label. Also in this way any additional relabeling on prometheus side will be not required.

**Comment by mrlhansen** [comment]
Hi @dmitry-sinina 

The `idrac_exporter_scrape_errors_total` is target specific (the number of scrape errors for the specific target). The `idrac_exporter_build_info` is indeed the same for all targets. However, I do not see any real value in changing the exporter because of a single metric being repeated for every target. You normally have this kind of information from every target anyway, it's just in this case it comes from the same binary (but some people do run one instance of the exporter per target).
