### ISSUE TITLE
Fine-Grained control over the exposed values

### ISSUE THREAD

**Issue by Roemer** [mrlhansen/idrac_exporter#33]
Currently, the settings for enabling / disabling statistics are more or less bound to redfish endpoints. Maybe that should be more fine-grained.
In my case, I for example do not need the cpu information at all. But they are bound to the system settings.
Maybe instead of `System`, there would be separate entries for:
- Bios
- Machine
- CPU
- System
- Health

And also for the sensors, maybe separate for
- Temperature
- Fan-Speed

Same for Power Supply, Usually I am inly interested in the effectively consumed watts.

And so on.

The background is:
If you have 10 servers, exporting the data every minute to VictoriaMetrics, every data you don't store helps keeping the space needed down. One could remove the data in the prometheus.yml but in my opinion, it is better to directly control this in the exporter itself.

Would you accept an MR that makes this much more configurable?

**Comment by mrlhansen** [comment]
The metrics are bound to Redfish endpoints, because there is a cost to scraping each endpoint. Once the endpoint is scraped, we might as well export as much information as possible, since it's for free.

When looking at exporters in general, they do allow you to select specific subsets of metrics (like this one does), but usually not each metric individually.

I do understanding your reasoning, but I think this is a bit too niche, especially considering that Prometheus already has a way of filtering out specific metrics. Is the space needed really an issue? I am scraping ~150 machines, using several different exporters, and I never really had any concern about storage space for this.
